services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes
    ports: ["5432:5432"]
    volumes: [db_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d votes"]
      interval: 2s
      timeout: 2s
      retries: 15

  api:
    build: .
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/votes
      - SQL_ECHO=0
      - TOPIC_TITLE=Aktiviteettipäivä 02.10.2025
    depends_on:
      db:
        condition: service_healthy
    ports: ["8080:8080"]
    restart: on-failure:3

volumes:
  db_data:
