version: "3.9"
services:
  ui-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    # If you host backend at http://localhost:8080 from your machine,
    # no special networking is needed; the browser hits it directly.
